services:
  homepage:
    build:
      context: .
      dockerfile: Dockerfile
    image: homepage:latest
    container_name: homepage
    ports:
      - "17834:8080"
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
